### ISSUE TITLE
what are the color options for the software interface?

### ISSUE THREAD

**Issue by Alon76** [Alon76/5starPOS#14]
I am wondering what my options are for changing the colors in the software. What is possible and what is not possible?
For example, can I change the order dialogue screen to white?
![colors](https://cloud.githubusercontent.com/assets/21187721/20407670/5c665932-ace0-11e6-835e-0f4567da2f4d.png)

**Comment by dalifreire** [comment]
@Alon76 I think it's possible to use any color that you desire. Just send me the color (the RGB value) and where do you want... and I'll try to do!

**Comment by Alon76** [comment]
Sorry for the delay, I had to deal with something. Do you have any experience with software gui design? Any recommendations?

**Comment by dalifreire** [comment]
Hi @Alon76, unfortunately no... design is not my best... :(

**Comment by Alon76** [comment]
I have made a few minor changes to the colours. let me know if you have any questions.
![kitchen screen colour](https://cloud.githubusercontent.com/assets/21187721/20716028/085b82c0-b61f-11e6-9742-5695140b71a0.png)
![order screen colours](https://cloud.githubusercontent.com/assets/21187721/20716029/08644f90-b61f-11e6-989f-ab601284f8ed.png)
![pay screen colours](https://cloud.githubusercontent.com/assets/21187721/20716030/0865938c-b61f-11e6-9ab5-4eb7a25a29e9.png)

**Comment by dalifreire** [comment]
Hi @Alon76, I'll take a look this weekend, ok?

**Comment by Alon76** [comment]
That's fine. I am still looking at the software to see what I want changed.

**Comment by dalifreire** [comment]
@Alon76, please take a look if it works as desired...

[#14_5starPOS.zip](https://github.com/Alon76/5starPOS/files/629693/14_5starPOS.zip)

**Comment by Alon76** [comment]
Everything looks good, but the kitchen screen is still the same?

**Comment by dalifreire** [comment]
Hi @Alon76, could you describe what we need to do in the kitchen screen?

**Comment by Alon76** [comment]
![kitchen screen colour](https://cloud.githubusercontent.com/assets/21187721/20892559/bb266c78-badc-11e6-8c7f-345ce2893a81.png)

**Comment by dalifreire** [comment]
@Alon76, done! Please, check if it works now.

[#14_5starPOS.zip](https://github.com/Alon76/5starPOS/files/632130/14_5starPOS.zip)

**Comment by Alon76** [comment]
Looks good. Thanks!
