### ISSUE TITLE
Separate back office from software and kitchen display.

### ISSUE THREAD

**Issue by Alon76** [Alon76/5starPOS#19]
I will only need one computer to have the back office functionality for each client. Is there a way to separate it from software, which would potentially make the software without the back office run lighter. As well, I would like to sell the kitchen display as a feature, so I need to be able to turn it off and on, without the clients being able to do that.

**Comment by Alon76** [comment]
I am wondering if it would be best to have 3 separate compiled software. One that is point of sale without back office and kitchen display. And then one with back office and another without back office and just kitchen display. For now we can just remove the back office button and kitchen display button. 

Does that work?

**Comment by dalifreire** [comment]
@Alon76, yes we can do this... but, for 3 separate software's, I think that will need a lot of work and we'll probably have a problem with the updates made by FloreantPOS team. We can compile 3 different versions (hiding the buttons) more fast... what do you think?

**Comment by Alon76** [comment]
That is actually what I meant, but I guess I didn't type it out properly. I was thinking just hiding the buttons and then compile the software again. 
Thanks

**Comment by Alon76** [comment]
So, just to sum up what I need. 

1) one with back office key hidden and kitchen display key hidden. 
2) one with just the kitchen display key hidden. 
3) one with back office key hidden.

**Comment by Alon76** [comment]
Got a question... Is there any way to build database replication into the software?

On Feb 16, 2017 7:27 PM, Dalí Freire <notifications@github.com> wrote:

@Alon76<https://github.com/Alon76>, yes we can do this... but, for 3 separate software's, I think that will need a lot of work and we'll probably have a problem with the updates made by FloreantPOS team. We can compile 3 different versions (hiding the buttons) more fast... what do you think?

**Comment by dalifreire** [comment]
@Alon76 If I understood your question.. yes, it is possible... but I think the most smart option is let the database do this...

**Comment by dalifreire** [comment]
@Alon76 Please, check if works as desired...

[#19_5starPOS.zip](https://github.com/Alon76/5starPOS/files/791984/19_5starPOS.zip)

**Comment by dalifreire** [comment]
Has done in the Issue #16.
