### ISSUE TITLE
Change categories layout in order screen

### ISSUE THREAD

**Issue by Alon76** [Alon76/5starPOS#3]
In each order screen (dine in, retail, takeout etc) there are categories for menu items. They run from top to bottom on the right hand side of the screen. The icons on the top right hand corner I want removed. This will make room for the second row of categories.
![categories](https://cloud.githubusercontent.com/assets/21187721/17952403/46835fd8-6a38-11e6-9a51-6b96c0282fa3.png)

**Comment by dalifreire** [comment]
@Alon76 I propose something a bit different here. Please, check if it works as desired.

[#3_5starPOS.zip](https://github.com/Alon76/5starPOS/files/441320/3_5starPOS.zip)

**Comment by Alon76** [comment]
It's not a bad idea. Let me work with it tomorrow and see how I like it. Is it easier that way?

**Comment by dalifreire** [comment]
@Alon76 This way the changes are a bit smaller. So, this make more easy to get changes from the community in the future.

**Comment by Alon76** [comment]
I used it for a bit and it works. Gonna close this.
