### ISSUE TITLE
Exit order screen

### ISSUE THREAD

**Issue by Alon76** [Alon76/5starPOS#7]
I need to remove the x from the screen, as it allows people to shutdown the system from the order screen, which is not good. Now that we removed the the functions in the top right, there is no way to exit that screen. I am always open to suggestions, so please feel free. 
![exit screen](https://cloud.githubusercontent.com/assets/21187721/18056119/9dd136f4-6dd8-11e6-834a-3c207d463f53.png)

**Comment by dalifreire** [comment]
@Alon76 I blocked the close button (x). Please, check if it works as desired....

[#7_5starPOS.zip](https://github.com/Alon76/5starPOS/files/540509/7_5starPOS.zip)

**Comment by Alon76** [comment]
Is there anyway to remove those three functions from the screen altogether? 

![image](https://cloud.githubusercontent.com/assets/21187721/19560976/bb63b300-96a4-11e6-8aec-fa8faba73963.png)

**Comment by dalifreire** [comment]
@Alon76 What are the three functions? I thought that in this task (#7 Exit order screen), you asked only for remove the close button (x).

**Comment by Alon76** [comment]
I guess I didn't make it clear. Right now they can still minimize and maximize...if it's easier, can you disable those three functions? 

![image](https://cloud.githubusercontent.com/assets/21187721/19562257/a2e964d2-96a9-11e6-8baa-2b654567fe41.png)

**Comment by dalifreire** [comment]
@Alon76 Yes, I can do this!

**Comment by Alon76** [comment]
There is also no way to exit that screen...any suggestions?

**Comment by dalifreire** [comment]
@Alon76 Try the "Cancel" button... I'm out of home to check now, but I think I implement this in the cancel button...

**Comment by Alon76** [comment]
Ok, no rush.

**Comment by dalifreire** [comment]
@Alon76 Please, check if it works as desired now.

[#7_5starPOS.zip](https://github.com/Alon76/5starPOS/files/543225/7_5starPOS.zip)

**Comment by Alon76** [comment]
Everything seems good.
