### ISSUE TITLE
Order screen

### ISSUE THREAD

**Issue by Alon76** [Alon76/5starPOS#8]
I want to remove that top part from every screen. Need a way to exit this screen since we remove the top part. Let me know what you suggest. 
![order screen](https://cloud.githubusercontent.com/assets/21187721/18056920/f07715b0-6ddb-11e6-8d50-3d253d505f82.png)

**Comment by dalifreire** [comment]
@Alon76, I'm working on this issue and I have finished almost all screen except "Orders" and "Home Delivery". Could you check if I'm in the right way. Thanks.

[#8_5starPOS.zip](https://github.com/Alon76/5starPOS/files/568035/8_5starPOS.zip)

**Comment by Alon76** [comment]
I don't see what changes were made?

**Comment by dalifreire** [comment]
@Alon76 I did remove the top part from all screens except these two: Orders and Home Delivery.

I'm thinking about these two screens because they not have a button that we can use as "back button".

**Comment by dalifreire** [comment]
@Alon76 Please, check if it works as desired.

[#8_5starPOS.zip](https://github.com/Alon76/5starPOS/files/574072/8_5starPOS.zip)

**Comment by Alon76** [comment]
It looks good. But, when I make an order and save it, then the order screen does not open and the system freezes. Do you have this issue?

**Comment by dalifreire** [comment]
@Alon76 I'll take a look... could you describe the details so I can reproduce this problem tonight?

**Comment by Alon76** [comment]
I went into home delivery. I created a new customer. Used that customer to create an order and paid for the order with cash. Then went to the first screen and tired to go into orders.

**Comment by dalifreire** [comment]
@Alon76 You are right! I found and fixed the problem. Please, could you check if it's good now?

[#8_5starPOS.zip](https://github.com/Alon76/5starPOS/files/576717/8_5starPOS.zip)

**Comment by Alon76** [comment]
Everything seems to be working now. Great work! Thanks!
