### ISSUE TITLE
Back office

### ISSUE THREAD

**Issue by Alon76** [Alon76/5starPOS#9]
I need some features that are only accessible when you hit another button on a different screen. I need to make the button back office on the first screen to go the screen you get when you hit the other button. 

![back office](https://cloud.githubusercontent.com/assets/21187721/18059027/06dba9b6-6de5-11e6-938a-27c9029ac144.png)

**Comment by dalifreire** [comment]
@Alon76 Please, check if it works.

[#9_5starPOS.zip](https://github.com/Alon76/5starPOS/files/560955/9_5starPOS.zip)

**Comment by Alon76** [comment]
Looks good. Thanks.
